# Generated by Django 4.1 on 2022-08-31 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('map', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Салоны',
                'verbose_name_plural': 'Салоны',
                'ordering': ['street'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ortopediya.category')),
            ],
            options={
                'verbose_name': 'подкатегории',
                'verbose_name_plural': 'подкатегории',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('art', models.CharField(default=0, max_length=50)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ortopediya.subcategory')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
                'ordering': ['subcategory'],
            },
        ),
        migrations.CreateModel(
            name='Index_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ortopediya.product')),
            ],
            options={
                'verbose_name': 'Продукты для слайдера главной страницы',
                'verbose_name_plural': 'Продукты для слайдера главной страницы',
                'ordering': ['id_product'],
            },
        ),
    ]
